package Ch8_Exception_Handling;

public class ExceptionTest {
    public static void main(String[] args) {
        System.out.println(args[0]); // 넘어오는 값이 없어서 컴파일 오류발생
    } 
}
